# Cloud Build Configuration for Vertice Chat Web App
# Deploy frontend (Next.js) and backend (FastAPI) to Cloud Run
# Triggered automatically on push to main branch

steps:
  # ============================================
  # Step 1: Build Backend Docker Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    dir: '.'

  # ============================================
  # Step 2: Build Frontend Docker Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'
    dir: '.'

  # ============================================
  # Step 3: Push Backend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend'
    waitFor: ['build-backend']

  # ============================================
  # Step 4: Push Frontend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend'
    waitFor: ['build-frontend']

  # ============================================
  # Step 5: Deploy Backend to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vertice-backend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production,FRONTEND_URL=https://vertice-frontend-nrpngfmr6a-uc.a.run.app'
      - '--set-secrets'
      - 'STRIPE_SECRET_KEY=stripe-secret-key:latest'
    waitFor: ['push-backend']

  # ============================================
  # Step 6: Deploy Frontend to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vertice-frontend'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '20'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '100'
      - '--clear-secrets'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_API_URL},NODE_ENV=production'
    waitFor: ['push-frontend']

# Artifact Registry images
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/backend:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/frontend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

# Substitution variables (can be overridden in trigger)
substitutions:
  _REGION: 'us-central1'
  _API_URL: 'https://vertice-backend-xxxxxxx-uc.a.run.app'

# Timeout for entire build
timeout: '1800s'
