steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/protovolt-studio/vertice/mcp-server:latest'
      - '-f'
      - 'prometheus/Dockerfile'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/protovolt-studio/vertice/mcp-server:latest'

timeout: 1200s
