substitutions:
  _REGION: 'us-central1'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/mcp-server:latest'
      - '-f'
      - 'Dockerfile.mcp'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/vertice-cloud/mcp-server:latest'

timeout: 1200s
