steps:
- name: 'hashicorp/terraform:1.9.0'
  entrypoint: 'sh'
  secretEnv:
  - 'TF_VAR_alloydb_initial_password'
  args:
  - '-c'
  - |
    cd infra/terraform
    terraform init

    echo "Checking for existing resources to import..."

    # Import VPC if exists
    terraform import -var="project_id=$PROJECT_ID" -var="region=us-central1" \
      google_compute_network.vertice_vpc projects/$PROJECT_ID/global/networks/vertice-vpc || echo "VPC already managed or not found"

    # Import Subnet if exists
    terraform import -var="project_id=$PROJECT_ID" -var="region=us-central1" \
      google_compute_subnetwork.vertice_subnet projects/$PROJECT_ID/regions/us-central1/subnetworks/vertice-subnet || echo "Subnet already managed or not found"

    # Import PSA if exists
    terraform import -var="project_id=$PROJECT_ID" -var="region=us-central1" \
      google_compute_global_address.private_ip_alloc projects/$PROJECT_ID/global/addresses/vertice-psa-range || echo "PSA already managed or not found"

    echo "Applying final configuration..."
    terraform apply -var="project_id=$PROJECT_ID" -var="region=us-central1" -auto-approve
  env:
  - 'PROJECT_ID=$PROJECT_ID'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/vertice-alloydb-initial-password/versions/latest
    env: 'TF_VAR_alloydb_initial_password'
