import React from 'react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { InfoIcon } from 'lucide-react';

interface AISafetyDisclaimerProps {
  className?: string;
  showIcon?: boolean;
}

export function AISafetyDisclaimer({ className, showIcon = true }: AISafetyDisclaimerProps) {
  return (
    <Alert className={`border-blue-200 bg-blue-50 ${className}`}>
      {showIcon && <InfoIcon className="h-4 w-4 text-blue-600" />}
      <AlertDescription className="text-blue-800">
        <strong>AI-Generated Content Notice:</strong> This response was generated by artificial intelligence.
        While we strive for accuracy and safety, AI can occasionally produce incorrect or inappropriate information.
        Please verify critical information independently.
        {' '}
        <a
          href="/system-card"
          className="underline hover:text-blue-600"
          target="_blank"
          rel="noopener noreferrer"
        >
          View our System Card for more details →
        </a>
      </AlertDescription>
    </Alert>
  );
}

export default AISafetyDisclaimer;