# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x03\x61\x32\x61\x1a\ntask.proto\x1a\rmessage.proto\x1a\x10\x61gent_card.proto\"W\n\x14SubscribeTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x17\n\x0finclude_history\x18\x02 \x01(\x08\x12\x15\n\rfrom_sequence\x18\x03 \x01(\x03\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xe5\x01\n\x13HealthCheckResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.a2a.HealthStatus\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x12<\n\ncomponents\x18\x04 \x03(\x0b\x32(.a2a.HealthCheckResponse.ComponentsEntry\x1a\x44\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0e\x32\x11.a2a.HealthStatus:\x02\x38\x01*\x81\x01\n\x0cHealthStatus\x12\x1d\n\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n\x17HEALTH_STATUS_UNHEALTHY\x10\x03\x32\x87\x04\n\nA2AService\x12@\n\x0bSendMessage\x12\x17.a2a.SendMessageRequest\x1a\x18.a2a.SendMessageResponse\x12\x43\n\x14SendStreamingMessage\x12\x17.a2a.SendMessageRequest\x1a\x10.a2a.StreamChunk0\x01\x12)\n\x07GetTask\x12\x13.a2a.GetTaskRequest\x1a\t.a2a.Task\x12:\n\tListTasks\x12\x15.a2a.ListTasksRequest\x1a\x16.a2a.ListTasksResponse\x12=\n\nCancelTask\x12\x16.a2a.CancelTaskRequest\x1a\x17.a2a.CancelTaskResponse\x12\x45\n\x14SubscribeTaskUpdates\x12\x19.a2a.SubscribeTaskRequest\x1a\x10.a2a.StreamChunk0\x01\x12\x43\n\x0cGetAgentCard\x12\x18.a2a.GetAgentCardRequest\x1a\x19.a2a.GetAgentCardResponse\x12@\n\x0bHealthCheck\x12\x17.a2a.HealthCheckRequest\x1a\x18.a2a.HealthCheckResponseB=\n\x0f\x63om.vertice.a2aB\x0cServiceProtoZ\x1cgithub.com/vertice/a2a/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.vertice.a2aB\014ServiceProtoZ\034github.com/vertice/a2a/proto'
  _globals['_HEALTHCHECKRESPONSE_COMPONENTSENTRY']._options = None
  _globals['_HEALTHCHECKRESPONSE_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHSTATUS']._serialized_start=428
  _globals['_HEALTHSTATUS']._serialized_end=557
  _globals['_SUBSCRIBETASKREQUEST']._serialized_start=67
  _globals['_SUBSCRIBETASKREQUEST']._serialized_end=154
  _globals['_HEALTHCHECKREQUEST']._serialized_start=156
  _globals['_HEALTHCHECKREQUEST']._serialized_end=193
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=196
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=425
  _globals['_HEALTHCHECKRESPONSE_COMPONENTSENTRY']._serialized_start=357
  _globals['_HEALTHCHECKRESPONSE_COMPONENTSENTRY']._serialized_end=425
  _globals['_A2ASERVICE']._serialized_start=560
  _globals['_A2ASERVICE']._serialized_end=1079
# @@protoc_insertion_point(module_scope)
