"""
Terraform Generator - Infrastructure as Code configurations.

Features:
- EKS cluster with managed node groups
- VPC with public/private subnets
- Remote state in S3 with locking
- Production-ready configuration
"""

import logging
from typing import Any, AsyncIterator, Dict

from .base import BaseGenerator

logger = logging.getLogger(__name__)


class TerraformGenerator(BaseGenerator):
    """Generate Terraform IaC configurations."""

    @property
    def name(self) -> str:
        return "terraform"

    async def generate(self, task_request: str) -> Dict[str, Any]:
        """Generate Terraform configuration."""
        logger.info("Generating Terraform configuration...")

        terraform = self._build_main_tf()

        return {
            "main.tf": terraform,
            "features": [
                "EKS cluster with managed node groups",
                "VPC with public/private subnets",
                "Remote state in S3 with locking",
                "Production-ready configuration",
            ],
        }

    async def generate_streaming(self, task_request: str) -> AsyncIterator[Dict[str, Any]]:
        """Generate Terraform configuration with streaming output."""
        yield {"type": "status", "data": "🏗️ Terraform Generator starting..."}

        yield {"type": "thinking", "data": "Generating main.tf with EKS + VPC...\n"}

        terraform = self._build_main_tf()

        yield {"type": "status", "data": "✨ Building production-ready infrastructure..."}

        yield {"type": "verdict", "data": "\n\n✅ Terraform configuration generated"}

        yield {
            "type": "result",
            "data": {
                "main.tf": terraform,
                "features": [
                    "EKS cluster with managed node groups",
                    "VPC with public/private subnets",
                    "Remote state in S3 with locking",
                ],
            },
        }

    def _build_main_tf(self) -> str:
        """Build main.tf content."""
        return """# Terraform Configuration - Production Grade
# Generated by DevOpsAgent

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
  }

  backend "s3" {
    bucket         = "your-terraform-state"
    key            = "infrastructure/prod/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}

# ============================================================================
# EKS Cluster
# ============================================================================
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.0"

  cluster_name    = "production-cluster"
  cluster_version = "1.28"

  cluster_endpoint_public_access = true

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_groups = {
    general = {
      min_size     = 3
      max_size     = 10
      desired_size = 3

      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
    }
  }

  tags = {
    Environment = "production"
    Terraform   = "true"
  }
}

# ============================================================================
# VPC
# ============================================================================
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "production-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b", "us-east-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = false

  tags = {
    Environment = "production"
  }
}

# ============================================================================
# Outputs
# ============================================================================
output "cluster_endpoint" {
  value = module.eks.cluster_endpoint
}

output "cluster_name" {
  value = module.eks.cluster_name
}
"""
