"""
CI/CD Pipeline Generator - GitHub Actions, GitLab CI, etc.

Features:
- Automated testing with coverage
- Docker multi-arch build
- GitOps deployment (ArgoCD)
- Zero manual steps
"""

import logging
from typing import Any, Dict

from .base import BaseGenerator

logger = logging.getLogger(__name__)


class CICDGenerator(BaseGenerator):
    """Generate CI/CD pipelines for various providers."""

    @property
    def name(self) -> str:
        return "cicd"

    async def generate(self, task_request: str) -> Dict[str, Any]:
        """Generate CI/CD pipeline based on provider."""
        logger.info("Generating CI/CD pipeline...")

        provider = self._detect_provider(task_request)

        if provider == "github":
            pipeline = self._build_github_actions()
        elif provider == "gitlab":
            pipeline = self._build_gitlab_ci()
        else:
            pipeline = self._build_github_actions()  # Default

        return {
            "pipeline": pipeline,
            "provider": provider,
            "features": [
                "Automated testing with coverage",
                "Docker multi-arch build",
                "GitOps deployment (ArgoCD)",
                "Zero manual steps",
                "Auto-rollback on failure",
            ],
        }

    def _detect_provider(self, request: str) -> str:
        """Detect CI/CD provider from request."""
        request_lower = request.lower()
        if "gitlab" in request_lower:
            return "gitlab"
        return "github"

    def _build_github_actions(self) -> str:
        """Build GitHub Actions workflow."""
        return """name: Production CI/CD Pipeline
# Generated by DevOpsAgent

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ============================================================================
  # JOB 1: Test
  # ============================================================================
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=. --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml

  # ============================================================================
  # JOB 2: Build & Push Docker Image
  # ============================================================================
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================================
  # JOB 3: Deploy via GitOps
  # ============================================================================
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: your-org/platform-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag
        run: |
          cd gitops/apps/api-service
          NEW_TAG="${{ github.sha }}"
          sed -i "s|image:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${NEW_TAG:0:7}|" deployment.yaml

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy main-${{ github.sha:0:7 }}"
          git push
"""

    def _build_gitlab_ci(self) -> str:
        """Build GitLab CI pipeline."""
        return """# GitLab CI/CD Pipeline
# Generated by DevOpsAgent

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt pytest pytest-cov
    - pytest --cov=. --cov-report=xml
  coverage: '/TOTAL.*\\s+(\\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://oauth2:$GITOPS_TOKEN@gitlab.com/your-org/platform-gitops.git
    - cd platform-gitops/apps/api-service
    - sed -i "s|image:.*|image: $DOCKER_IMAGE|" deployment.yaml
    - git commit -am "Deploy $CI_COMMIT_SHORT_SHA"
    - git push
  only:
    - main
"""
