# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmessage.proto\x12\x03\x61\x32\x61\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto"\x82\x02\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04role\x18\x02 \x01(\x0e\x32\x10.a2a.MessageRole\x12\x18\n\x05parts\x18\x03 \x03(\x0b\x32\t.a2a.Part\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncontext_id\x18\x05 \x01(\t\x12\x0f\n\x07task_id\x18\x06 \x01(\t\x12,\n\x08metadata\x18\x07 \x03(\x0b\x32\x1a.a2a.Message.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xbb\x02\n\x0bStreamChunk\x12(\n\nevent_type\x18\x01 \x01(\x0e\x32\x14.a2a.StreamEventType\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x03\x12\x14\n\ntext_delta\x18\x04 \x01(\tH\x00\x12\x1f\n\x07message\x18\x05 \x01(\x0b\x32\x0c.a2a.MessageH\x00\x12!\n\x08\x61rtifact\x18\x06 \x01(\x0b\x32\r.a2a.ArtifactH\x00\x12.\n\rstatus_update\x18\x07 \x01(\x0b\x32\x15.a2a.TaskStatusUpdateH\x00\x12\x1b\n\x05\x65rror\x18\x08 \x01(\x0b\x32\n.a2a.ErrorH\x00\x12-\n\ttimestamp\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\t\n\x07\x63ontent"D\n\x10TaskStatusUpdate\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x05*s\n\x0bMessageRole\x12\x1c\n\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n\x11MESSAGE_ROLE_USER\x10\x01\x12\x16\n\x12MESSAGE_ROLE_AGENT\x10\x02\x12\x17\n\x13MESSAGE_ROLE_SYSTEM\x10\x03*\xe3\x01\n\x0fStreamEventType\x12!\n\x1dSTREAM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n\x1fSTREAM_EVENT_TYPE_STATUS_UPDATE\x10\x01\x12#\n\x1fSTREAM_EVENT_TYPE_MESSAGE_CHUNK\x10\x02\x12%\n!STREAM_EVENT_TYPE_ARTIFACT_UPDATE\x10\x03\x12\x1b\n\x17STREAM_EVENT_TYPE_ERROR\x10\x04\x12\x1f\n\x1bSTREAM_EVENT_TYPE_HEARTBEAT\x10\x05\x42=\n\x0f\x63om.vertice.a2aB\x0cMessageProtoZ\x1cgithub.com/vertice/a2a/protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"\n\017com.vertice.a2aB\014MessageProtoZ\034github.com/vertice/a2a/proto"
    )
    _globals["_MESSAGE_METADATAENTRY"]._options = None
    _globals["_MESSAGE_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_MESSAGEROLE"]._serialized_start = 718
    _globals["_MESSAGEROLE"]._serialized_end = 833
    _globals["_STREAMEVENTTYPE"]._serialized_start = 836
    _globals["_STREAMEVENTTYPE"]._serialized_end = 1063
    _globals["_MESSAGE"]._serialized_start = 70
    _globals["_MESSAGE"]._serialized_end = 328
    _globals["_MESSAGE_METADATAENTRY"]._serialized_start = 281
    _globals["_MESSAGE_METADATAENTRY"]._serialized_end = 328
    _globals["_STREAMCHUNK"]._serialized_start = 331
    _globals["_STREAMCHUNK"]._serialized_end = 646
    _globals["_TASKSTATUSUPDATE"]._serialized_start = 648
    _globals["_TASKSTATUSUPDATE"]._serialized_end = 716
# @@protoc_insertion_point(module_scope)
