# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import agent_card_pb2 as agent__card__pb2
from . import message_pb2 as message__pb2
from . import service_pb2 as service__pb2
from . import task_pb2 as task__pb2


class A2AServiceStub(object):
    """=============================================================================
    A2A SERVICE
    =============================================================================

    A2A Protocol gRPC Service.

    Primary interface for agent-to-agent communication.
    Supports both unary and streaming RPC methods.
    ==========================================================================
    MESSAGE OPERATIONS
    ==========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
            "/a2a.A2AService/SendMessage",
            request_serializer=task__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=task__pb2.SendMessageResponse.FromString,
        )
        self.SendStreamingMessage = channel.unary_stream(
            "/a2a.A2AService/SendStreamingMessage",
            request_serializer=task__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=message__pb2.StreamChunk.FromString,
        )
        self.GetTask = channel.unary_unary(
            "/a2a.A2AService/GetTask",
            request_serializer=task__pb2.GetTaskRequest.SerializeToString,
            response_deserializer=task__pb2.Task.FromString,
        )
        self.ListTasks = channel.unary_unary(
            "/a2a.A2AService/ListTasks",
            request_serializer=task__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=task__pb2.ListTasksResponse.FromString,
        )
        self.CancelTask = channel.unary_unary(
            "/a2a.A2AService/CancelTask",
            request_serializer=task__pb2.CancelTaskRequest.SerializeToString,
            response_deserializer=task__pb2.CancelTaskResponse.FromString,
        )
        self.SubscribeTaskUpdates = channel.unary_stream(
            "/a2a.A2AService/SubscribeTaskUpdates",
            request_serializer=service__pb2.SubscribeTaskRequest.SerializeToString,
            response_deserializer=message__pb2.StreamChunk.FromString,
        )
        self.GetAgentCard = channel.unary_unary(
            "/a2a.A2AService/GetAgentCard",
            request_serializer=agent__card__pb2.GetAgentCardRequest.SerializeToString,
            response_deserializer=agent__card__pb2.GetAgentCardResponse.FromString,
        )
        self.HealthCheck = channel.unary_unary(
            "/a2a.A2AService/HealthCheck",
            request_serializer=service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=service__pb2.HealthCheckResponse.FromString,
        )


class A2AServiceServicer(object):
    """=============================================================================
    A2A SERVICE
    =============================================================================

    A2A Protocol gRPC Service.

    Primary interface for agent-to-agent communication.
    Supports both unary and streaming RPC methods.
    ==========================================================================
    MESSAGE OPERATIONS
    ==========================================================================
    """

    def SendMessage(self, request, context):
        """Send a message to the agent (unary).
        Creates or continues a task based on the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendStreamingMessage(self, request, context):
        """Send a message and receive streaming response.
        Returns incremental chunks as the agent processes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """==========================================================================
        TASK OPERATIONS
        ==========================================================================

        Get a task by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTasks(self, request, context):
        """List tasks with optional filtering."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelTask(self, request, context):
        """Cancel an in-progress task."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubscribeTaskUpdates(self, request, context):
        """Subscribe to task updates (server streaming)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAgentCard(self, request, context):
        """==========================================================================
        DISCOVERY OPERATIONS
        ==========================================================================

        Get agent card for discovery.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check endpoint."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_A2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=task__pb2.SendMessageRequest.FromString,
            response_serializer=task__pb2.SendMessageResponse.SerializeToString,
        ),
        "SendStreamingMessage": grpc.unary_stream_rpc_method_handler(
            servicer.SendStreamingMessage,
            request_deserializer=task__pb2.SendMessageRequest.FromString,
            response_serializer=message__pb2.StreamChunk.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=task__pb2.GetTaskRequest.FromString,
            response_serializer=task__pb2.Task.SerializeToString,
        ),
        "ListTasks": grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=task__pb2.ListTasksRequest.FromString,
            response_serializer=task__pb2.ListTasksResponse.SerializeToString,
        ),
        "CancelTask": grpc.unary_unary_rpc_method_handler(
            servicer.CancelTask,
            request_deserializer=task__pb2.CancelTaskRequest.FromString,
            response_serializer=task__pb2.CancelTaskResponse.SerializeToString,
        ),
        "SubscribeTaskUpdates": grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeTaskUpdates,
            request_deserializer=service__pb2.SubscribeTaskRequest.FromString,
            response_serializer=message__pb2.StreamChunk.SerializeToString,
        ),
        "GetAgentCard": grpc.unary_unary_rpc_method_handler(
            servicer.GetAgentCard,
            request_deserializer=agent__card__pb2.GetAgentCardRequest.FromString,
            response_serializer=agent__card__pb2.GetAgentCardResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=service__pb2.HealthCheckRequest.FromString,
            response_serializer=service__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("a2a.A2AService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class A2AService(object):
    """=============================================================================
    A2A SERVICE
    =============================================================================

    A2A Protocol gRPC Service.

    Primary interface for agent-to-agent communication.
    Supports both unary and streaming RPC methods.
    ==========================================================================
    MESSAGE OPERATIONS
    ==========================================================================
    """

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/SendMessage",
            task__pb2.SendMessageRequest.SerializeToString,
            task__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SendStreamingMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/a2a.A2AService/SendStreamingMessage",
            task__pb2.SendMessageRequest.SerializeToString,
            message__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/GetTask",
            task__pb2.GetTaskRequest.SerializeToString,
            task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListTasks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/ListTasks",
            task__pb2.ListTasksRequest.SerializeToString,
            task__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CancelTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/CancelTask",
            task__pb2.CancelTaskRequest.SerializeToString,
            task__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubscribeTaskUpdates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/a2a.A2AService/SubscribeTaskUpdates",
            service__pb2.SubscribeTaskRequest.SerializeToString,
            message__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetAgentCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/GetAgentCard",
            agent__card__pb2.GetAgentCardRequest.SerializeToString,
            agent__card__pb2.GetAgentCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/a2a.A2AService/HealthCheck",
            service__pb2.HealthCheckRequest.SerializeToString,
            service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
