"""
planner/formatting.py: Plan Formatting Utilities.

Pure functions for formatting plans as markdown and other outputs.
Extracted from PlannerAgent for modularity.

Following CODE_CONSTITUTION.md: <500 lines, 100% type hints.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List


def format_plan_as_markdown(
    plan_data: Dict[str, Any],
    goal: str,
) -> str:
    """
    Format plan as structured markdown with checkboxes.

    Args:
        plan_data: Plan dictionary with stages, sops, etc.
        goal: The goal/task request string

    Returns:
        Markdown formatted plan string
    """
    lines = [
        "# Execution Plan",
        "",
        f"**Goal:** {plan_data.get('goal', goal)}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"**Confidence:** {plan_data.get('confidence_summary', 'Not calculated')}",
        "",
        "---",
        "",
        "## Strategy Overview",
        "",
        f"{plan_data.get('strategy_overview', 'Sequential execution of planned steps.')}",
        "",
    ]

    # Add clarifying questions and responses
    questions = plan_data.get("clarifying_questions", [])
    responses = plan_data.get("clarification_responses", [])
    if questions:
        lines.extend(["## Clarifications", ""])
        response_map = {r.get("question_id"): r.get("answer") for r in responses}
        for q in questions:
            answer = response_map.get(q.get("id"), "Not answered")
            lines.append(f"- **Q:** {q.get('question', 'Unknown')}")
            lines.append(f"  - **A:** {answer}")
        lines.append("")

    # Add stages/steps with checkboxes
    lines.extend(["## Execution Steps", ""])

    stages = plan_data.get("stages", [])
    sops = _extract_steps(plan_data)

    if stages:
        lines.extend(_format_stages(stages))
    elif sops:
        lines.extend(_format_sops(sops))

    # Add risk assessment
    lines.extend(
        [
            "## Risk Assessment",
            "",
            f"**Level:** {plan_data.get('risk_assessment', 'MEDIUM')}",
            "",
            f"**Rollback Strategy:** {plan_data.get('rollback_strategy', 'Restore from last checkpoint')}",
            "",
            "## Resources",
            "",
            f"- **Estimated Duration:** {plan_data.get('estimated_duration', 'Unknown')}",
            f"- **Token Budget:** {plan_data.get('token_budget', 'Unknown')}",
            f"- **Max Parallel Agents:** {plan_data.get('max_parallel_agents', 1)}",
            "",
            "---",
            "",
            "*Generated by PlannerAgent v6.0*",
        ]
    )

    return "\n".join(lines)


def _extract_steps(plan_data: Dict[str, Any]) -> List[Any]:
    """Extract steps from plan data with multiple fallback keys."""
    return (
        plan_data.get("sops")
        or plan_data.get("steps")
        or plan_data.get("tasks")
        or plan_data.get("actions")
        or (plan_data.get("plan") if isinstance(plan_data.get("plan"), list) else None)
        or []
    )


def _format_stages(stages: List[Dict[str, Any]]) -> List[str]:
    """Format stages with their steps."""
    lines = []
    for stage in stages:
        lines.append(f"### {stage.get('name', 'Stage')}")
        lines.append("")
        lines.append(f"*{stage.get('description', '')}*")
        lines.append("")
        for step in stage.get("steps", []):
            lines.extend(_format_step(step))
        lines.append("")
    return lines


def _format_sops(sops: List[Any]) -> List[str]:
    """Format SOP steps."""
    lines = []
    for i, step in enumerate(sops, 1):
        step_data = _normalize_step(step, i)
        lines.extend(_format_step(step_data))
    lines.append("")
    return lines


def _normalize_step(step: Any, index: int) -> Dict[str, Any]:
    """Normalize step to consistent dict format."""
    if isinstance(step, str):
        return {
            "id": f"step-{index}",
            "action": step,
            "role": "executor",
            "confidence_score": 0.7,
            "definition_of_done": "Completed",
        }
    elif isinstance(step, dict):
        conf = step.get("confidence_score") or step.get("confidence") or 0.7
        try:
            conf = float(conf)
        except (ValueError, TypeError):
            conf = 0.7
        return {
            "id": step.get("id") or step.get("step_id") or f"step-{index}",
            "action": (
                step.get("action")
                or step.get("description")
                or step.get("task")
                or step.get("name")
                or "No description"
            ),
            "role": step.get("role") or step.get("agent") or "executor",
            "confidence_score": conf,
            "definition_of_done": (
                step.get("definition_of_done")
                or step.get("done_when")
                or step.get("success_criteria")
                or "Completed"
            ),
        }
    else:
        return {
            "id": f"step-{index}",
            "action": str(step),
            "role": "executor",
            "confidence_score": 0.7,
            "definition_of_done": "Completed",
        }


def _format_step(step: Dict[str, Any]) -> List[str]:
    """Format a single step as markdown lines."""
    confidence = step.get("confidence_score", 0.7)
    conf_emoji = "G" if confidence >= 0.8 else "Y" if confidence >= 0.6 else "R"
    return [
        f"- [ ] **{step.get('id')}** ({step.get('role')}): {step.get('action')}",
        f"  - [{conf_emoji}] Confidence: {confidence:.0%}",
        f"  - Done when: {step.get('definition_of_done', 'Completed')}",
    ]


def generate_confidence_summary(overall_confidence: float) -> str:
    """Generate human-readable confidence summary."""
    if overall_confidence >= 0.9:
        return f"VERY HIGH ({overall_confidence:.0%}) - Plan is well-understood with low risk"
    elif overall_confidence >= 0.7:
        return f"HIGH ({overall_confidence:.0%}) - Good understanding, manageable risk"
    elif overall_confidence >= 0.5:
        return f"MODERATE ({overall_confidence:.0%}) - Some uncertainty, may need adjustments"
    elif overall_confidence >= 0.3:
        return f"LOW ({overall_confidence:.0%}) - Significant uncertainty present"
    else:
        return f"SPECULATIVE ({overall_confidence:.0%}) - High risk, consider alternatives"


__all__ = [
    "format_plan_as_markdown",
    "generate_confidence_summary",
]
